### ISSUE TITLE
Adding Video Information to all Video Folders

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-cg#128]
We should add https://github.com/w3c/wot-cg/blob/main/Tutorials/whatiswot/Project_Details/video-information-template.md to all folders so that we can use that information when publishing to YouTube.

**Comment by handealptekin** [comment]
Should I be adding the .md files in a single pull request? Also, should I write a "Specific Description" for each video, or should it be left empty for now?

**Comment by egekorkan** [comment]
> Should I be adding the .md files in a single pull request?

Yes, since we have sort of agreed on the content

**Comment by egekorkan** [comment]
PR #129 has addressed this largely but I have noticed some improvements.

- We should add the Discord link to all videos.
- The description sentence is copied from the videos (as agreed) but looking at it now, it sounds a bit weird. So we should just reformulate each to start with "This video talks about xyz..."

Once those are done, we can close this issue
