### ISSUE TITLE
Feedback/remarks on Video #1 to #9

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-cg#138]
Sometimes the text (along the audio) hides the slide/content.
e.g.,  Video 1 at 2:39, Video 3 at 2:58, Video 4 at 0:36 etc etc
I suggest to make sure that slides don't use the lower part of the content

Video 2 at 1:54
I would update the date... having the year 2016 seems somewhat *old* ;-)

Video 2 at 2:08
missing commas between CBOR, TExt, and Audio 

Video 2 at 3:31
nesting of JSON snippet is a bit broken and some quotes are different/invalid (see base)

Video 4 at 0:58
JSON snippet not poperly formatted 

Video 4 at 1:40
speaks about validation error.. but I think it is a syntax error instead 

Video 9 at 3:38
Listing HTTP, WebSocket and CoAP should be limited with commas ","

**Comment by egekorkan** [comment]
Tutorial call on 26.01: @handealptekin will do one PR for all that the preview links and then we can have a discussion on the PR. I will also watch all videos one last time before pushing on YouTube.

**Comment by egekorkan** [comment]
The issues are addressed, closing
